version: '3.9'

services:
  web:
    container_name: django_app
    build: .
    command: bash -c "pipenv install --deploy --ignore-pipfile && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
